apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbadges-mcp
  labels:
    app: bitbadges-mcp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bitbadges-mcp
  template:
    metadata:
      labels:
        app: bitbadges-mcp
    spec:
      containers:
        - name: bitbadges-mcp
          image: trevormil23/bitbadges-mcp:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PRODUCTION
              value: 'true'
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
