apiVersion: v1
kind: Service
metadata:
  name: bitbadges-mcp
spec:
  type: ClusterIP
  selector:
    app: bitbadges-mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
